sudo: false
language: node_js
node_js:
- 7
script:
- node_modules/.bin/shortcake test
# after_success:
# - node_modules/.bin/shortcake coverage
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    secure: U/ZMJAeq6AmHSOpQbd2j2GLfq7Y7fBvONcKZcx9KEvh0ANEmeeL+5Gmi9OnQCozbn4CTlkNYvMwKQvZaz0pKmfaB2nrxs8arfJboDSoF+VVBIjJMvdAmZ1xxqeJ8bIVTma4hQ/tT7zjIrHhE6jf4tIwbav2JlMsVo99E+C8H1In10mLVN0FRoqFVnOENpSY89IgqX2SkulmMje92l33polWHHw8RK40CbeWF7fbkQ0Bc1U/0NFU8FSsLh23XxsvyUkeL6+ifNrReZuRTsoL1EGaE9uRJpQKxYLisP9WiXmIUGF2whT7Q8ea5AqBGRy+4fBlZ4J4LAigqaP53bxU4eYUNwOm6qux4JsYDsevLp1tPqQt2op0Rl/UsL0gSc6qcI0zkdNkJB9FrQIs06y4RT1aLP95Cf1GJ3k2JJWvJrttdtXxmBjkJGeyNEQ7ug5BYpYNEvdKtsIk4jZFxpy7sB9J0bsenUs8EC9sT5gyeWlcQDxNzkYruHxOoHW++YAInE5/TEJYag8PDgNUOAohTCR/KLrbppj2uCRYgx3z1EFNWGOVHKH2lz8s4/uUPf+JsDPgNtcyyEU0Hn0m8yYc2KKuZT3loqD1fbxEy7TNxMGhCrjad6xwINe/5zhgPNhHvoXTcm6BJtu2mPez5e8uJMy7+vIF1OBSb3Rubg6fkgYw=
env:
  global:
  - CXX=g++-4.8
  - secure: RfK0aCfEXMS3VYJlwWCRvlC6uwMChf5c5CCF7C40RMT4e7PRMkeqgxTZnPXOoeunaC9/RenYkdNNqK5W8/5dt3JL/iQfJKQpHpnP56CdKbjVXYRXECdJWin7wXL3ZNe038kaD7cUlkMWC5XWe8TkYCJgTrsJ6etweMCL2UbLyM82cudqmwe92U44IltCpyYUxyQ6OCdJ8evpwwmWyfW9aszJxj9VUk1lH2L1F8wzMQk/PO7y+F73h2ryTcLeYeViJf2plY4NhnhETaJ4AgpMfOH2B1Yfj8lqS/vYOk6+LlfTZxuSNL1TSylykaJmOzh+f69UHHGETa517A6uBJuTTW39/up22SCw06Tf9eCzdevlrg5B2bqSKTiYLkgVPxN2yt/cUL8xzxt70IuALAjcdLxnEzmSGsOTJCx5/dvxwgZPlBP/0fpDIP9AgNOgQe7P3TVrAP+FJW+Nm+VUPHIPlmiw6Ji6ihxsYo6qVstGu1fh8SkvA4G4YDs2BO7cUrBiMadrjX/n8larn7kxlcu/o6ZcJZrLrfJBJsLjmQHiObBglm6dCMSJkAJEtASHQHYJ6ZlyAmQADw4DetZJ9Hdt9ueY7U7NDbRstcoqZVXWOUDVmeh+2TcXxhINE/sPQh6UW4U9BLlBYYFgXgL24TUo6E75y+8NHxBgEWNbGHwQnNQ=
  - secure: hY5f+p81oXwng19Pv0EWnytBAzknAVcWSPzm54zkJNE+L6BTAwyFokL4BkSL5D0pJXZn6z91XsPHpDMZDHga63TjT3jsMIdWAS12dmtOvbrBCf/suvuFHPRruG/ghn1dALU2ovlk1DdlWfH18EnFcVzIKNm6CoD055CI+e2m12sjt59ZATK4G7kgarbfPTnwqYmvRbErQxy6R0qwYLKvzkPDNizwELMGsMIY7ftQQT0H/7jhKIuDfO8ITjBRTVqks3JZlpvan7IhXz0RzmrTieNFWVOprvKWkOa2CRctCGiRq83X7Yfjxf53MBy0Gq95nQ5ByCnIztzFu5g8w4VyMKnBNaiCaXi6vnfcDMTpEt52VwAJebCH/y5lvkYXwwzMcdlArghN9byNGf5N8+Lvx/8i2qy53bqzeW70X2KPZp0575YX5VhRFWY7xxllkqVSUi4T/MJlsaoLLc6fsdkqsU9cOkw5dxIfeAJEeuG0AxwM33B3I7yHbUmWAt8n+Dz2IT86kdudeiNMIdPReosRs4f6StPo995oUpXwQrGayIBjeyt+2VMqRLGGwrxYVo2qO2DdusazGtMeWYPmXQl8rEu57gGiw9Nwiwqf1gYx1AZJjEgW8yHcFRAayaDiK6QwsiwZvFkF0UERlxpKv6KpZo/cYTRfOs6Mk8YWJO1UV/o=
before_install:
- export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
